[theme]
#background = "black"
primary = "light white"
secondary = "light black"
title = "red"
playing = "red"
playing_bg = "black"
highlight = "light white"
highlight_bg = "black"
error = "light white"
error_bg = "green"
statusbar = "black"
statusbar_progress = "red"
statusbar_bg = "red"
cmdline = "light white"
cmdline_bg = "black"
